#!/usr/bin/bash

# file_name=$(echo $1 | perl -lne '/.*?(?=\.)/g && print $&')

# May you need to change below -L or -I if you have it somewhere else

g++  $1 -o renrem \
     -std=c++11 -Wall -Weffc++ -Wextra -pedantic -Wfatal-errors -pedantic-errors \
     -L/usr/local/lib -I/usr/local/include/boost \
     -l boost_regex

     

